---
- name: Add docker repo
  ansible.builtin.yum_repository:
    file: docker-ce
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/rhel/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/rhel/gpg
    owner: root
    group: root
    mode: '0644'
    state: present

- name: Install docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  ignore_errors: '{{ ansible_check_mode }}'

- name: Enable and start docker.service
  ansible.builtin.systemd_service:
    name: docker.service
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
...
